### ISSUE TITLE
multithreading bug of refcounting

### ISSUE THREAD

**Issue by trouger** [tomerfiliba/rpyc#137]
Assume `d` is a netref of a remote dict, the following line may raise `KeyError` in `rpyc/lib/colls.py` (`RefCountingColl.__getitem__`) when executing in a working thread:
```python
d.get("a", [])
```

Here is the explanation:
1. The list object `[]` is boxed(added into `conn._local_objects`) and sent to the remote side. The working thread blocks waiting for the reply of `d.get("a", [])`.
2. On the remote side, a netref of the list object is created. Because `"a"` is not in `d`, the remote side returns the netref of the list object to the local side.
3. The netref of the list object is garbage collected and an `aync_request` of `HANDLE_DEL` is sent to the local side.
4. On the local side, the network "message queue" has the following two messages in the correct order: (1)reply of the `d.get("a", [])` call, which contains the id of the local list object, (2)a request to delete the local list object.
5. On the local side, there is a `BgServingThread` which processes messages. The working thread receives the first of the above two messages, and before dispatching the reply, the `BgServingThread` gets scheduled. The `BgServingThread` receives and dispatches the second message, i.e., deletes the list object from `conn._local_objects`.
6. When the working thread gets scheduled, it dispatches the reply, trying to get the list object from `conn._local_objects` by object id, and a `KeyError` is raised.

**Comment by coldfix** [comment]
I think this exact scenario can not anymore happen anymore due to 4c8f00429af08cf60d67368115976a43b556efff:

- when we are at point 5 in this command sequence, `_dispatch` is called in order for the two messages. This method unboxes the message and with it the object itself, before the `HANDLE_DEL` has a chance of ever running.
- at point 6, the handler now executes the message with the previously unboxed object without error

Let me know if you think that I'm wrong.

Best, Thomas
