### ISSUE TITLE
pymongo and rpyc

### ISSUE THREAD

**Issue by capaulson** [tomerfiliba/rpyc#165]
I'm trying to use pymongo out of IronPython, and I'm having issues. For a simple example, I just want to extract the database names:

The code:

``` python
import rpyc
c = rpyc.classic.connect('localhost', port=12345)
pymongo = c.modules['pymongo']
conn = pymongo.MongoClient('localhost')
print conn.database_names()
```

This returns the following from IronPython: 

Message: 'Database' object is not callable. If you meant to call the 'exposed_database_names' method on a 'MongoClient' object it is failing because no such method exists.

This works perfectly under 'regular' python, which is running a classic server. Any ideas on why this doesn't work or what the error message means?

**Comment by coldfix** [comment]
Hi, quick note:

This issue occurs on CPython as well and is not in any way specific to IronPython or windows.

The reason is the `__getattr__` implementation of `MongoClient` that returns a `Database` object if asked for a non-existing attribute. Since we try for `exposed_database_names` before we try for `database_names` itself, we always run into this case.

Possible server-side fixes:
- set `config['allow_exposed_attrs'] = False` in the server application, globally. However, this may break other parts of your program
- override `Connection._check_attr` to not use `exposed_prefix` when accessing a `MongoClient` instance. However, this is too specific for inclusion in rpyc..
