### ISSUE TITLE
Question: issues with multiple concurrent clients?

### ISSUE THREAD

**Issue by chris-hailstorm** [tomerfiliba/rpyc#219]
The tool looks brilliant, just trying to understand it.  Could not find this point in the doco.

When a client references a server-side object, how does that relate to other clients referencing the same object? Are there thread-safety issues, such as don't reference global objects or ??

Or to put it another way -- we are all familiar with the issues when multiple clients use the same API in for example a Flask REST API -- there is a request context that isolates each client / request from all others.  What's the equivalent issue for rpyc?

Thanks

**Comment by coldfix** [comment]
There is no builtin protection against race-conditions due to accessing the same server-side object on multiple clients and nor is it even possible to do in full generality. So if you do need to concurrent access to some mutable object, you have to protect it on your own.

Does this answer the question? Otherwise, can you be more specific?
