### ISSUE TITLE
How to use rpycd.py

### ISSUE THREAD

**Issue by hgz6536** [tomerfiliba/rpyc#231]
why affter  excuted rpycd.py, there was no any rpyc process in my system ?

**Comment by coldfix** [comment]
You don't provide much information, but if I had to guess, there was a runtime error and the script terminated.

I just quickly checked on the file and had multiple issues. To be honest I don't believe it is mature yet.

First, it shows an `ModuleNotFoundError: No module named 'daemon'`. Okay, that's easy, just `pip install python-daemon`, nothing to concern.

After that's done, I reexecute the script and it goes to background, no error message, just like a successful daemonization would look like. However, trying to connect a client fails "Connection refused". The supposed logfile `/var/log/rpycd.log` doesn't exist either. Maybe this is the behaviour you observed.

Ok, I open up the source code and remove the `with daemon.DaemonContext(...)` lines to ensure that I will get all output that would be swallowed in the daemon.

Now, the next problem manifests: `configparser.NoSectionError: No section: 'rpycd'`. Apparently, the script doesn't look for the default `.conf` file in its own directory, so I change directory into `bin` and execute again.

Now I get `PermissionError: [Errno 13] Permission denied: '/var/log/rpycd.log'`. This one can be fixed by specifying a logfile path that is writeable by the current user in the config file.

After this, the script seems to work when executed in foreground. However, activating the `DaemonContext` again, it doesn't work. I add one line that is executed before `start()` and should just touch a file in `/tmp`. Nothing. This looks to me like a problem in the `python-daemon` module.

Feel free to investigate further, submit pull-requests, open issues elsewhere and so on. It might take me a while to get back to this.
