### ISSUE TITLE
 RPYC ForkingServer  AttributeError: 'module' object has no attribute 'SIGCHLD'

### ISSUE THREAD

**Issue by yehiasalah** [tomerfiliba/rpyc#235]
i got this error  from method  ForkingServer  
        in __init__
    self._prevhandler = signal.signal(signal.SIGCHLD, self._handle_sigchld)
      AttributeError: 'module' object has no attribute 'SIGCHLD'

**Comment by coldfix** [comment]
On which OS? What's your python version?

**Comment by yehiasalah** [comment]
Thank you for your interest,
I am working on Windows 10 OS with python version 2.7

**Comment by coldfix** [comment]
Hi, I'm afraid `ForkingServer` is only for POSIX compatible platforms (as the docstring says). Windows doesn't have `signal.SIGCHLD` nor `os.fork`, so that's off the hook.

It might be possible to implement using `multiprocessing.Process` which is available on windows too. However, note that `multiprocessing` is a lot slower on windows because there is no real native forking (instead it will be emulated by some startup code that loads all the relevant modules etc on startup). Nevertheless, I would accept pull-requests for that.

Best, Thomas
