### ISSUE TITLE
RegistryServer on_service_removed() not called

### ISSUE THREAD

**Issue by geiranton** [tomerfiliba/rpyc#238]
I would expect the on_service_removed() to be called whenever a service instance is removed,just like the add behaviour, but as it is implemented it is called only when all service instances for a service are pop'ed. Is this correct? I would have moved the  self.on_service_removed(name, addrinfo) outside the if.

`class RegistryServer .....

     def _remove_service(self, name, addrinfo):
        """removes a single server of the given service"""
        self.services[name].pop(addrinfo, None)
        if not self.services[name]:
            del self.services[name]
            try:
                self.on_service_removed(name, addrinfo)
            except Exception:
                self.logger.exception('error executing service remove callback')`

**Comment by coldfix** [comment]
Hi,

I think both are valid events. I guess the line of thought here behind the naming scheme is that a service is removed once there is no server left providing it.

If you need a `on_server_removed` event, you can simpliy add it before the `if`. I'm also open to accept a PR for that (and/or for a better `on_service_removed` docstring).

Best, Thomas

**Comment by geiranton** [comment]
The on_service_added() is called for each new addrinfo added so the behaviour of the two differs.
addrinfo not in self.services[name]
vs 
not self.services[name]

**Comment by coldfix** [comment]
You are right. I didn't check the inconsistency.

We should definitely change the behaviour of either `on_service_added` or `on_service_removed`. I don't really care which.

The easiest fix would be `git revert` 0eaa0840 from which the change originated. This patch was merged in #173 resolving #172.

@stirlingboy69 can you elaborate if/why you needed this behaviour. Should we rather revert `on_service_removed` or alter `on_service_added`?

Personally, I'm for reverting, since the new behaviour wasn't even in a release until 5 months ago.

**Comment by geiranton** [comment]
I have some remote test nodes which are registering themselves on a central test server (find the rpyc excellent for this purpose :-) ). The central server web gui got a (json-rpc) signal whenever a remote node appears or disappears,  the change will be reflected in the list of test nodes. 
 If I read it correct I would also prefer to revert the  0eaa084  .

**Comment by coldfix** [comment]
Okay, I think since @stirlingboy69 is not responding, the best option is to revert his patch here.
