### ISSUE TITLE
Integrating with Blender UI Event Loop

### ISSUE THREAD

**Issue by nathan5280** [tomerfiliba/rpyc#257]
I'm working to integrate a remote client with the Blender 3D Studio.  I've done this with Pyro, but want to take advantage of the RPyC Classic server to access the Blender Python API.  It looks like I have a straight path to doing this when I run Blender headless as everything is driven by the Python interpreter in Blender.  When I run the headed version there is an event loop that keeps the UI alive.  If the blender interpreter starts the RPyC server, then the calls from RPyC run on a different thread than the UI and cause problems in Blender.

With Pyro I was able to set a timer in Blender that calls Pyro periodically and services any client requests.  When there are no more client requests, the server times out on the socket and returns control to Blender.  In this model client request are run on the Blender event loop thread and everything continues to work fine.

It seems like I need a new Server class that has a method to call when it is time to check for client requests that I can just hook into the Blender timer.  It seems like someone else must have come across this scenario before and I like to learn from their experience before I start hacking the server code myself.

Does anyone have suggestions on how to do something similar with RPyC?

**Comment by coldfix** [comment]
Hi,

rather than customizing a server class that times that runs in the same thread as the blender loop, I'd recommend running a standard server in another thread, but proxying the blender API to post messages into your GUI thread. It shouldn't be too hard to do this generically. This way, you let your system handle the context switch between blender/rpyc rather than implementing your own (which would probably waste more time waiting in blender or rpyc even if there is nothing to do).
