### ISSUE TITLE
How can I get the ip (or the host name) and the port of the client trying to connect?

### ISSUE THREAD

**Issue by dnlbazac** [tomerfiliba/rpyc#260]
Hello.

I need a server that is able to identify the clients attempting to connect. The simplest way of doing that is by IP (name) and port. I started analyzing the on_connect method of the rpyc.Service.
I got to the Connection object but I did not find the ip (or host name) or the port.

I know I could expose a function on the clients that would return the IP and the port but this is not elegant at all.

I guess that should be straightforward but I was not able to find it,
Please tell me what is the way you recommend for obtaining the IP (or name) and the port of the client who asking for a connection.

Thank you in advance.

**Comment by coldfix** [comment]
Hi, rpyc doesn't have a builtin function for this, but it should be easy enough using [socket.getpeername](https://docs.python.org/3/library/socket.html#socket.socket.getpeername) from the stdlib:


```python
socket.getpeername(conn._channel.stream.sock)
```

**Comment by dnlbazac** [comment]
Your solution implies accessing the protected member _channel of the conn object.
The law of Demeter is also violated.
This is not clean OOP.

**Comment by coldfix** [comment]
> Your solution implies accessing the protected member _channel of the conn object.
> The law of Demeter is also violated.
> This is not clean OOP.

Oh snap! If that's the worst part of your code-base, I want you coding for me right now! ;)

Luckily, there are no protected members in python - you are free to do anything you feel confident to deal with (which I consider a big advantage over C++ in fact). As you are probably aware this just means it's considered an implementation detail that may change between versions. Yet in fact, this member is presumably more stable than other parts of the (public) API that are subject to change for the next major version, so we could remove the understore. However, I'm thinking anyway about substantially changing `Connection` to separate the socket serving logic from rpyc protocol.

Alternatively, you may consider subclassing `Server._accept_method(sock)` which receives the socket as its argument. Will probably not fit nicely into your application logic either. (Furthermore, I may change the `Server` class as well, since I dislike how it combines low level connection handling with forking method in the same class).

Just remember, one line doesn't make a program bad and not all problems fit into all notions of "clean OOP".

> Do you think of exposing the IP and port in another way in the future?

You are free to suggest a clean API and submit a PR for that. Since I like clean code as well (not necessarily OOP though), I will oppose any solution that moves further complexity into rpyc or require violating demeter internally without providing a clear benefit. I think a minor demeter violation like the above is inherent to solve your problem with the current structure of rpyc (unless you want to work on a larger API refactoring) - and I'd rather let it be on the user side than integrate into rpyc's public API and thus promise to keep it there since others start depending on it (e.g. naïvely adding a getter for the remote IP on the connection object would feel completely out of place and if such a method were present already, I would hate it and schedule it for removal the next chance I get).

**Comment by dnlbazac** [comment]
Hello, Thomas.
Thank you for the details.
I agree with you, I had overwritten the _accept_method. Hoping for a better solution, I asked you this question.
If you are talking about the fact the Server may use a Service instance or a Service class then, yes, I was also wondering about this.

By the way, most of the documentation is describing the 3.5 version, but that one is not available. Isn't it better to describe the version available?

I have one more question for you: how do you suggest extracting data from the service?
I extend a ThreadPoolServer to which I pass a MyService class. I can't pass anything to the MyService instances in RPyC 3.4.4 (right?)  so the MyService does not have a pointer to the parent (or to the outside world). When an MyService exposed function is called, a value is received in that function. My ThreadPoolServer needs that value. What is the best way of getting it?

Thank you.
