### ISSUE TITLE
Unable to authenticate using custom authenticator function

### ISSUE THREAD

**Issue by mmeade** [tomerfiliba/rpyc#266]
I'm trying to lock my connections down with a password and added the function Authenticate to the server:

def Authenticator(sock):
  logging.info('In authenticator with %s', sock)
  if select.select([sock], [], [], 1)[0]:
    data = sock.recv(26)
    if not data:
      logging.info('Sock not readable')
      raise authenticators.AuthenticationError('No credentials sent')
    else:
      credentials += data
  else:
    logging.info('Sock closed')
    raise authenticators.AuthenticationError('No credentials sent')

  logging.info('credentials: %s', credentials)
  if credentials in _CREDENTIALS and _CREDENTIALS[credentials] >= time.time():
    del _CREDENTIALS[credentials]
    logging.info('authenticated')
    return sock, None
  raise authenticators.AuthenticationError('Wrong credentials')

I'm unable to figure out how to pass the credentials from the client to the server on connection. I've tried both connection and ssl_connection (but wasn't using keys, just to try) by passing in config={'credentials': credentials} without it working.

The authenticator gets triggered but the socket returns an empty string.

The documentation shows how to use a custom authenticator method but only briefly mentions ssl_connection and the 'credentials' key, but doesn't have an example from the client side.

Any help would be appreciated.

**Comment by szabgab** [comment]
For the sake of clarity I think it would be better to put your code snippets in between triple-backticks to show the proper indentation. See "Syntax highlighting" in https://guides.github.com/features/mastering-markdown/ for

**Comment by coldfix** [comment]
Hi,

I didn't read your example in detail as
- its hardly readable (no formatting);
- you didn't give any information about version, etc
- you didn't show your client code

Did you try the example on http://rpyc.readthedocs.io/en/latest/docs/secure-connection.html#ssl? 

From your question, I believe you tried to pass `credentials` in the config on the client side. However, the documentation states that this field only holds the credentials that were actually passed by the remote side. In order to pass credentials, you need to send them manually over the socket before instanciating the connection, see e.g. the implementation of [ssl_connect](http://rpyc.readthedocs.io/en/latest/_modules/rpyc/utils/factory.html#ssl_connect).

From a quick glimpse I can also tell you that calling raw `recv` on a socket is a recipe for problems, since this doesn't give any guarantees about the length of data that is retreived at once.
