### ISSUE TITLE
How to send functions?

### ISSUE THREAD

**Issue by andreafioraldi** [tomerfiliba/rpyc#271]
Hi guys,
I want to pass a callback function to a remote function and execute the sended function in the remote machine and not locally.

for example:
```python
>> def callback(a,b):
    print a,b
    return a+b
>> #type(remote_caller) is netref
>> remote_caller(callback, 4, 5)
>> #4 5 is not printed here but in the remote machine
```
Thanks :)

**Comment by coldfix** [comment]
Did you try `rpyc.utils.classic.teleport_function`?

**Comment by andreafioraldi** [comment]
No, thanks it's perfect.
Can i use modules that i know that are imported in the server in the teleported function?

**Comment by coldfix** [comment]
Which modules are "imported" depends on the execution scope.

What teleport currently does is:
- try to import `f.__module__` on the remote side if it exists, i.e. the module that the function is defined in
- fallback to the servers `__main__` module
- execute the function in the corresponding scope

Thanks for putting focus on this. IMO, at least the first option doesn't make much sense since this is presumably primarily useful for ad-hoc created functions and in cases where the module does not exist on the remote. Furthermore, the fallback logic can lead to surprising effects.

IMO, it makes probably more sense to execute teleported functions in `conn.namespace` instead, i.e. the same scope that is used for `conn.eval` and `conn.exec`. This would simplify preparing an environment by e.g.:
- importing modules remotely: `conn.execute('import os')`
- teleporting multiple co-dependent functions, e.g.:

```python
def foo():
  print("foo")

def bar():
  print("bar")
  foo()

teleport_function(conn, foo)
teleport_function(conn, bar)
```

What do you think?
