### ISSUE TITLE
Creating a Self killing rpyc service

### ISSUE THREAD

**Issue by tarun2107** [tomerfiliba/rpyc#273]
I am running rpyc classic server (forking mode) , with many clients connecting to same.
Wanted to know if it's possible for the server to terminate itself if no client has sent any request over a specified period of time?

##### Environment
- rpyc version : 3.4
- python version : 2.7
- operating system : MAC_OS

**Comment by coldfix** [comment]
Hi, there is no builtin mechanism for this. However, you could subclass the Server and override the `_handle_connection` method to invoke `rpyc.core.protocol.Connection.serve` with a defined timeout in a loop (instead of calling `serve_all`). You may also need to override `_access_method` to add some means to communicate between the service threads/processes/... for different clients.

An alternative approach is to use the brand-new gevent based server to register a function for periodical execution that will check for recent activity and shut down the server otherwise.

**Comment by tarun2107** [comment]
I added following command line parameters while launching rpyc server:
```
  maxTimeout=cli.SwitchAttr("--killTimeout", cli.Range(0, 65535), default = None, help="Specify the kill time to use; "the default is none", group = "Time")
 enableAutoKill=cli.Flag(["--autoKill"], help = "Enable UTT AutoKill", group = "AutoKill")	
```
Then in the main method, I do this:
```
    def main(self):        
        if self.enableAutoKill is True:
            self.autoKill()
```
The autoKill() method runs a daemon thread, which periodically makes some check whether some client activity is happening or not, if no client activity is past "maxTimeout: period, then it kills the entire process grp.

**Comment by Evidlo** [comment]
@coldfix How would you recommend doing this with a `Service`?

Is there a way to access the socket from inside `on_connect` or `on_disconnect`?  It might be possible to do something with `sock.settimeout()` to achieve this.

**Comment by Evidlo** [comment]
This isn't exactly what I wanted, but it's close enough that it works.  Instead of the shutdown timer starting at the last activity or when the last client disconnects, it starts when a client connects.

### Server
``` python
import rpyc
from rpyc.utils.server import ThreadedServer
import socket
import sys
import errno
from rpyc.lib.compat import get_exc_errno


class MyService(rpyc.Service):

    def exposed_foobar(self, s):
        return s + ' world'


class MyServer(ThreadedServer):

    def accept(self):
        """Copied from rpyc server.py"""

        while self.active:
            try:
                sock, addrinfo = self.listener.accept()
                # timeout after client connects
                self.listener.settimeout(5)
            except socket.timeout:
                # instead of passing, quit
                sys.exit()
            except socket.error:
                ex = sys.exc_info()[1]
                if get_exc_errno(ex) in (errno.EINTR, errno.EAGAIN):
                    pass
                else:
                    raise EOFError()
            else:
                break

        if not self.active:
            return

        sock.setblocking(True)
        self.logger.info("accepted %s with fd %s", addrinfo, sock.fileno())
        self.clients.add(sock)
        self._accept_method(sock)

if __name__ == '__main__':
    t = MyServer(
        MyService,
        port=1234,
        protocol_config={"allow_public_attrs":True},
        # initial timeout before any client connects
        listener_timeout=5
    )
    t.start()
```

### Client
``` python

import rpyc
import time

# works
conn = rpyc.connect('localhost',1234)
print(conn.root.foobar('hello'))

time.sleep(2)

# works
conn = rpyc.connect('localhost',1234)
print(conn.root.foobar('hello'))

time.sleep(6)

# server has timed out, ConnectionRefusedError
conn = rpyc.connect('localhost',1234)
print(conn.root.foobar('hello'))
```

I tried fiddling with `conn._channel.stream.sock.settimeout()` inside `on_disconnect` in the service, but it doesn't seem to affect the listener timeout.
