### ISSUE TITLE
Large data structures transmit inefficiently as netref

### ISSUE THREAD

**Issue by dirkroorda** [tomerfiliba/rpyc#279]
When a client asks a large dictionary or list from the server, it gets a netref shadow object back.
Only when it accesses an item in the dict or list, the data of that item will be sent over the line.
This causes a hefty performance penalty.

In my case, the innocent loop:

```
for element in data:
   do something with element
```

took a long time if `data` is a list or dictionary with say a million items.
Even when the client and the server are on the same machine.

It goes much better when the server pickles the dict or list, or converts it to a tuple of items first.

It would be nice if one could somehow instruct the client/server to transmit the real object, not a shadowed netref object.

Anyway, it took me quite some time to bump into this fact, and I think it is helpful to point out this performance penalty in the docs, including the work-around.

Otherwise I'm enjoying the rpyc package greatly, and it really helped me to get up and running with this kind of processing really quickly.

**Comment by coldfix** [comment]
Hi, thanks for the feedback!

> It would be nice if one could somehow instruct the client/server to transmit the real object, not a shadowed netref object.

There is currently no opcode for that. If you use classic service, you could consider `rpyc.utils.classic.obtain` on the client side. If you don't, you could decorate the critical service methods with a decorator such as this:

```python
def pickle_result(func):
  def wrapped(*args, **kwargs):
    return pickle.dumps(func(*args, **kwargs))

class Service(rpyc.Service):
  @pickle_result
  def foo(self):
    ...
    return a_large_datastructure
```

On the downside, using `pickle` will enable effictively arbitrary code execution on whomever side the data is unpickled. If you don't want that, you have to choose some other serialization library that suits your needs and security concerns. The builtin `rpyc.core.brine` handles only very basic, immutable python types such as numbers, tuples and frozen sets, but no dicts.

> Anyway, it took me quite some time to bump into this fact, and I think it is helpful to point out this performance penalty in the docs, including the work-around.

Could you propose a concrete patch for the docs where/how you would have liked to read about this issue?

Best, Thomas

**Comment by dirkroorda** [comment]
I'm still not sure how rpyc transmits data.
For example, if I transmit a tuple with a million members, it seems that rpyc is transferring them element by element, which is slow.
If I wrap the tuple in a string before sending, and unwrap it after receiving, it goes much faster.
Even faster is it when I pickle the tuple before sending, and unpickle it after receiving.
But them I thought: why is rpyc not pickling the tuple for me on its own. 
I saw the protocol config `allow_pickle` default `False`, so I set it to `True`, but that did not do the trick.

**Comment by coldfix** [comment]
rpyc does not transmit tuples individually, but rather uses `rpyc.core.brine` for de-/serialization as mentioned above. This is better than transmitting individually over the network, but since it is written in python of course also much slower than pickle or other serialization frameworks written in C.

If a suitable pull-request is provided, I'm open for either
- allowing the user to choose their own serialization framework 
- adding an optimized variant of brine (written e.g. in C/cython)

The `allow_pickle` option does not itself control whether `pickle` is used for serialization, but rather enables the client to use `pickle.dump` on a netref.

**Comment by dirkroorda** [comment]
But even if I serialize by joining the tuple members into a tab separated string, it goes must faster than brine.
AHA: looking into the code of `brine`: 
```
**Brine** is a simple, fast and secure object serializer for **immutable** objects.
The following types are supported: ``int``, ``long``, ``bool``, ``str``, ``float``,
``unicode``, ``bytes``, ``slice``, ``complex``, ``tuple`` (of simple types),
``frozenset`` (of simple types) as well as the following singletons: ``None``,
``NotImplemented``, and ``Ellipsis``.
```
So it does not handle tuples of tuples well! And that is exactly what I am bitten by.

Why not just use pickle? It is in the standard library. If there are security issues, maybe let the user opt in.

**Comment by coldfix** [comment]
> But even if I serialize by joining the tuple members into a tab separated string, it goes must faster than brine.

str.join is very fast.

> So it does not handle tuples of tuples well!

As I said, it does handle nested tuples. The problem is that it's implemented in python.

> Why not just use pickle?

For classic service it could make sense. For any new-style service, using `pickle` will enable arbitrary code execution and completely negate any attempt to communicate securely.

Also, don't forget that we still need boxing/unboxing (netrefs), which should have comparable overhead as the python serialization layer, so it's not even a priori clear how much benefit replacing `brine` by `pickle` will have, maybe it's much less than you see in your tests (you are welcome to measure). If you don't want boxing/unboxing, just use pickle on your own or a different library altogether.

> If there are security issues, maybe let the user opt in.

As I said, you are welcome to submit a suitable patch.

**Comment by dirkroorda** [comment]
Thanks Thomas,
indeed by pickling myself before transmitting, everything works fine. I have not encountered other libraries that do big interprocess data transfer better.
I suspect that my use case (big data transfer) is not typical for the purposes of rpyc: transparency in coding between processes.
I keep using rpyc!
Dirk
