### ISSUE TITLE
ThreadPoolServer not working rpyc 4.0

### ISSUE THREAD

**Issue by AlinMH** [tomerfiliba/rpyc#283]
Hello,

I am having some issues on using **ThreadPoolServer**. The client cannot connect to the server, and gives the following error.

But it happens to work on **rpyc 3.4.4** really well. And I don't know if I'm using the **ThreadPoolServer** properly, it may be my fault.

```
Traceback (most recent call last):
  File "C:/.../RPyCTest/client_rpyc.py", line 3, in <module>
    con = rpyc.connect('localhost', 7777)
  File "C:\...\AppData\Local\Programs\Python\Python35\lib\site-packages\rpyc\utils\factory.py", line 93, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "C:\...\AppData\Local\Programs\Python\Python35\lib\site-packages\rpyc\core\stream.py", line 154, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "C:\...\AppData\Local\Programs\Python\Python35\lib\site-packages\rpyc\core\stream.py", line 112, in _connect
    s.connect(sockaddr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

##### Environment

- rpyc version 4.0
- python version 3.5
- operating system Windows 7

##### Minimal example

Server:

```python
import rpyc
import threading

class SomeService(rpyc.Service):
    def on_connect(self, conn):
        print("connected with connection %s" % conn)


server = rpyc.ThreadPoolServer(service=SomeService, port=7777)
t = threading.Thread(target=server.start)
t.start()

```

Client:

```python
import rpyc

con = rpyc.connect('localhost', 7777)
```

**Comment by coldfix** [comment]
Hi, thanks for the report and sorry to respond so late..

I bisected and found the reason in 3a3d0ec5ae300501: since ThreadPoolServer, sets `self.active = True` before starting up, the check in `Server._listen` returns before setting the socket in listen mode. This can be fixed by removing the check, or (perhaps preferrably) restructure `ThreadPoolServer` to start its thread in `_listen`. This will remove the need to set `active = True` in `__init__`.

I will take care of this.

Best, Thomas

**Comment by AlinMH** [comment]
Thanks ! :D
