### ISSUE TITLE
rpyc is awesome... and quite chatty.  might be a way to fix that....

### ISSUE THREAD

**Issue by delandtj** [tomerfiliba/rpyc#294]
```
okaaay, so i've just spent about 10 days writing and debugging 
something absolutely horrendously complex that looks like a
 dog threw up on the keyboard, which just so happens to 
*massively* reduce the dynamic loading and walking of python 
objects, cacheing properties so that they are only fired off *on demand*.

it was nothing like as simple as just dropping in a lazy property: 
just as in BaseNetref it was necessary to overload __getattribute__ and __dir__.

however, unlike BaseNetref, properties are *not* just dropped 
into place immediately: they're dropped instead into a special
 __subgetters__ dictionary (which would need to be put into
 the __slots__ of BaseNetref, with a wrapper class instance 
around the *actual* object-that-we-WILL-want...

consequently ONLY when the attribute is ACTUALLY needed does it get created.

here's the really critical bit: there is also an overload of __dir__ 
which will return the keys of the __subgetters__ dictionary 
(the properties that have NOT been instantiated yet) merged with 
the properties that HAVE already been instantiated
(by calling object.__dir__(self)).

would anyone be interested to help out debugging / checking if the
 same trick can be applied to rpyc, with a view to reducing
 the amount of network traffic?
```

**Comment by coldfix** [comment]
Hi, I absolutely agree that rpyc is too chatty in many places and I would like to see this improved where possible.

Concerning lazy attribute access, I had already thought about something similar as well. The problem is that this changes semantics compared to how rpyc currently works (i.e. side-effects from descriptors apply immediately; `hasattr` works as expected, `type(x) is type(y)` performs as expected as well), so this couldn't be the default in any case (unless I misunderstood your thoughts..). Maybe it can be requested explicitly similar to how `rpyc.async_(...)` currently works, e.g.: `rpyc.lazy(netref).foo.bar.xyz()` will do all attribute accesses as well as the function call in a single step.

There are also other places where rpyc will send too many messages, e.g.:
- it requests typeinfo for each encountered user type individually when one is unboxed
- it can request typeinfo for the same class multiple twice if the peer's answer hasn't arrived or hasn't been processed yet

Maybe this could be improved by letting the user send typeinfo for many expected types in a single message up front, or alternatively send typeinfo when boxing a certain type the first time (rather than putting the responsibility on the client during unboxing)

**Comment by comrumino** [comment]
Tracking at #326
