### ISSUE TITLE
sklearn function hangs

### ISSUE THREAD

**Issue by dilzeem** [tomerfiliba/rpyc#300]
##### Environment

- rpyc version 4.02
- python version 3.6.6
- operating system Windows 10

##### Minimal example

Server:

```python
import rpyc
rpyc.lib.setup_logger()


from sklearn import datasets
from sklearn.model_selection import cross_val_predict
from sklearn import linear_model

class MyService(rpyc.Service):
    def on_connect(self, conn):
        pass

    def on_disconnect(self, conn):
        pass

    def exposed_predict(self):
        lr = linear_model.LinearRegression()
        boston = datasets.load_boston()
        y = boston.target
        predicted = cross_val_predict(lr, boston.data, y, cv=10)
        return predicted


    def exposed_predict_arg(self, data):
        boston = data
        lr = linear_model.LinearRegression()
        y = boston["target"]
        predicted = cross_val_predict(lr, boston["data"], y, cv=10)
        return predicted


if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(MyService, port=18861)
    t.start()
```

When I run `c.root.predict()` the data is returned and `cross_val_predict(lr, boston["data"], y, cv=10)` is able to run.

Client:
However this does

```python
import rpyc
c = rpyc.connect("localhost", 18861)

from sklearn import datasets
results = c.root.predict()
```

However when I pass the data (boston) to server and call `c.root.predict_arg(boston)` I get a time out error, and it seems to hang at  `cross_val_predict(lr, boston["data"], y, cv=10)` 

Client:
This doesn't work

```python
import rpyc
c = rpyc.connect("localhost", 18861)

from sklearn import datasets
boston = datasets.load_boston()

results = c.root.predict_arg(boston)
```

Stacktrace

```
TimeoutError                              Traceback (most recent call last)
<ipython-input-137-3a865ab8ff07> in <module>()
      1 boston = datasets.load_boston()
      2 
----> 3 results = c.root.predict_arg(boston)

c:\home\.virtualenvs\all-hzimeryf\lib\site-packages\rpyc\core\netref.py in __call__(_self, *args, **kwargs)
    197         def __call__(_self, *args, **kwargs):
    198             kwargs = tuple(kwargs.items())
--> 199             return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
    200         __call__.__doc__ = doc
    201         return __call__

c:\home\.virtualenvs\all-hzimeryf\lib\site-packages\rpyc\core\netref.py in syncreq(proxy, handler, *args)
     73     """
     74     conn = object.__getattribute__(proxy, "____conn__")
---> 75     return conn.sync_request(handler, proxy, *args)
     76 
     77 def asyncreq(proxy, handler, *args):

c:\home\.virtualenvs\all-hzimeryf\lib\site-packages\rpyc\core\protocol.py in sync_request(self, handler, *args)
    469         """
    470         timeout = self._config["sync_request_timeout"]
--> 471         return self.async_request(handler, *args, timeout=timeout).value
    472 
    473     def _async_request(self, handler, args = (), callback = (lambda a, b: None)):

c:\home\.virtualenvs\all-hzimeryf\lib\site-packages\rpyc\core\async_.py in value(self)
     93         here. Otherwise, the result is returned directly.
     94         """
---> 95         self.wait()
     96         if self._is_exc:
     97             raise self._obj

c:\home\.virtualenvs\all-hzimeryf\lib\site-packages\rpyc\core\async_.py in wait(self)
     45             self._conn.serve(self._ttl)
     46         if not self._is_ready:
---> 47             raise AsyncResultTimeout("result expired")
     48 
     49     def add_callback(self, func):

TimeoutError: result expired
```

**Comment by coldfix** [comment]
Hi,

I would guess this is caused by the `sync_request_timeout` setting (being too low). This should probably be set to a higher value by default in rpyc (or even reworked completely, to look for TCP timeouts, not timeouts for the current result). Otherwise, you will get timeout errors for all long running computations.

As you show, the computation itself is short enough to not trigger timeout errors if the dataset is loaded on the server. However, when passing `boston` to `predict_arg`, what actually happens is that a netref to the local `boston` object is passed to the server. Whenever the server now tries to access some element of the dataset (which presumably may happen many times), a request will be sent to the client, asking for the corresponding data. This can significantly increase the computation time due to network latency. The result is that the operation may be so slow to appear hanging until you run in the timeout error.

Assuming this is the only error, you may try to deliver the dataset to the server first. In classic mode this can be achieved by simply calling `c.root.predict_arg(rpyc.classic.deliver(boston))`, which makes use of `pickle` and is therefore not available in non-classic mode. In your case, you would have to write the corresponding serialization routine manually:

```python

class MyService(rpyc.Service):
  def exposed_deserialize_dataset(self, dataset):
    """Receive a dataset from serialized data."""
    return deserialize(dataset)

  # .. other routines


# serialization, assuming here datasets are numpy arrays:
import numpy as np
import io

def serialize(array):
  with io.BytesIO() as f:
    np.save(f, array)
    return f.getvalue()

def deserialize(data):
  with io.BytesIO(data) as f:
    return np.load(f)

def deliver(conn, dataset):
  """Delivers dataset to server and returns netref to it."""
  return conn.root.deserialize_dataset(serialize(boston))


# client code

boston = datasets.load_boston()
results = c.root.predict_arg(deliver(boston))
```

**Comment by dilzeem** [comment]
Thanks for getting back to me. 

I ended up going with the classical rpyc and managed to get it worked.

**Comment by jgomezlopez** [comment]
I'm experiencing a similar behaviour with classification methods in scikit learn. Using the classical rpyc and running LogisticRegression algorithm, the server in async and sync mode is frozen during training. The same happens with classification methods. The same dataset is used for training in a standalone version without rpyc. The training process is done in less than a second.

Any clue about what is happening?

Thanks in advance for your help.
