### ISSUE TITLE
rpyc server blocks 

### ISSUE THREAD

**Issue by andrewhack** [tomerfiliba/rpyc#315]
HI,

First, thank for your work - even I dind't explored everything, this software provides a lot of possibilities.
I am sorry if I am missing something but I will explain as much as possible what is my issue.
I am trying to integrate RPYC in existing software. 
I am aware that RPYC server is using blocking method that's why I tried to use a separate thread to initialize the server but even in this case the main loop is blocked. This is the general description of the code:

------------------------------------------------------------------------------------------
def rpc(self):
     rpch=rpyc.utils.server.ThreadedServer(RPCService, port=rpcport)
     rpch.start()

while (True)
     # other code

     th1=threading.Thread(target = rpc)
     th1.daemon=True
     th1.start()
      
      #other code
------------------------------------------------------------------------------------------

Am I using the library in a wrong way?

Thank you in advance

**Comment by mihai-dobre** [comment]
you can do threading.Thread(target=rpch.start). There is no need to wrap the RPyC server in a method. Also, you might need the server variable to check for different attributes. And yes it's blocking at the second loop(when the while loop executes the second time) because the server it already running, the port is already in use.
You should ask this kind of questions on StackOverflow. This is not a library bug/issue.
