### ISSUE TITLE
Cannot connect to 4.0.2 service from 4.1

### ISSUE THREAD

**Issue by astraw38** [tomerfiliba/rpyc#330]
Remote slave service:

```
 pip3 show rpyc
Name: rpyc
Version: 4.0.2
```

And the exception on the local machine:

```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 594, in _handle_inspect
    return tuple(netref.inspect_methods(self._local_objects[oid]))
  File "/usr/lib/python3.7/site-packages/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: (7696561775896, 'SlaveService', 'rpyc.core.service')
```

Local machine rpyc:
```
 pip show rpyc
Name: rpyc
Version: 4.1.0
```

**Comment by comrumino** [comment]
Thank you for the concern. However, per the release notes.
```
Requests/replies are not compatible between >=4.1.0 and earlier versions
```
This was a known change in compatibility. The break in backwards compatibility could be more clear with [version checking](https://github.com/tomerfiliba/rpyc/issues/327#issuecomment-497159543) and communicating this to the user.

The main reason for this change was to address `isinstance` across connections to respect the transparency promise of the library. In order to support `isinstance` across connections of object instances one would have to transfer the entire object, redo the caching mechanisms, or as I chose to change the OID to an ID pack which would support `instancecheck`. Transfer the object seemed inefficient and to defeat the purpose of using proxies. Redoing the caching mechanism would likely introduce unintended object leaks. So, the convention changed from OID to an ID pack at the cost of breaking backwards compatibility, but added benefits as well.

ID packs should increase the frequency of cache hits compared to using the object ID as before. An ID Pack which includes the class id, the object id, and the `module_name.class_name` whereas the OID was one of these.

Hopefully this clears up the reasoning for the change. Feel free to follow up with questions if desired.

**Comment by astraw38** [comment]
I had checked the changelog in the docs first, didn't see that at all. 

I will complain about backwards compatibility changes not being between major versions though. For example, 3 not working with 4 would make more sense, rather than a minor version bump breaking lots of things.

**Comment by comrumino** [comment]
:100:  [Semantic versioning](https://semver.org/) would agree with you. Sorry about that, it just seemed silly to jump from 4.0.2 to 5.0.0. I'll follow semantic versioning closer moving forward.

**Comment by xNinjaKittyx** [comment]
This is a little unfortunate that there's no clear error. I was clued in by the changelogs, but I would suggest changing the changelog to explicitly mention the incompatibility of 4.10.

```
Note - Requests/replies are not compatible between >=4.1.0 and earlier versions
```

This is really vague, and my first instinct was to think that a specific feature was broken.

Because there is no good Exception given by RPyC, there should be an explicit statement in the changelogs mentioning that you cannot connect a client/server >= 4.10 with a client/server < 4.10

**Comment by comrumino** [comment]
@xNinjaKittyx, throwing a more clear exception is on the road map :smiley:

I can be more precise when writing the change long. I'm thinking
`Convention change (OID to ID Pack) prevents connection between a client/server version >= 4.10 with a client/server version < 4.10`

I appreciate the feedback all.

**Comment by traverseda** [comment]
You really shouldn't break backwards compatibility for minor releases.

**Comment by comrumino** [comment]
Closing this issue since the discussion is exhausted, but feel free to reopen this issue as needed.
