### ISSUE TITLE
Function teleportation across Python versions

### ISSUE THREAD

**Issue by Jongy** [tomerfiliba/rpyc#370]
I've tried to use `teleport_function` today (which is one of the most magical, amazing features I've encountered); the server runs on Python 3.8 and the client runs on Python 3.7.

Teleportation fails due to the change in a5f146a36a02da0492db6e3d40c673ccd33a05b4.

I was wondering if the lack of cross-support is intentional? It's an easy fix to be backward & forward compatible, I'd be happy to create a PR to support client 3.7 -> server 3.8 and vice versa. (Though, of course there might be bytecode differences. You get a nice `SystemError` in that case and it's sometimes solvable, so I still find it useful)

**Comment by comrumino** [comment]
The reason the changes made in `a5f146a` are due to a change made in [upstream](https://bugs.python.org/issue37032)---pardon my terrible commit message. Of course, I welcome PRs. I only have two sticking points:
* quality of the work matches the existing code base (i.e. flake8 and reasonable design)
* unit tests prove the change in behavior (makes my life easier)
If you have any questions along the way, feel free to ask and I'll do my best to be helpful. Thanks a ton!

**Comment by Jongy** [comment]
Yeah I understand the commit, my wording of "due to ..." was wrong because before your change there wasn't even support for teleportation in 3.8, anyway.

Cool then, I'll work on it and submit a PR.

**Comment by comrumino** [comment]
Thanks again! As a side note, I did did write some unit tests when reviewing your PR and they're committed at d08cdc7.
